Disable "check cache locations" step in github CI

diff --git a/.github/workflows/packcheck.yml b/.github/workflows/packcheck.yml
--- a/.github/workflows/packcheck.yml
+++ b/.github/workflows/packcheck.yml
@@ -454,29 +454,31 @@ jobs:
         echo "$PACKCHECK $PACKCHECK_COMMAND BUILD_POST_DEPS=y"
         bash -c "$PACKCHECK $PACKCHECK_COMMAND BUILD_POST_DEPS=y"
 
-    - name: Check cache locations
-      shell: bash
-      run: |
-        # We want to see if any cache paths are symlinks; e.g. on github
-        # ~/.ghcup is a pre-existing symlink to /usr/local.
-        if [ "$RUNNER_OS" == "Windows" ]; then
-          # Convert Windows paths to Unix-style for Bash
-          APPDATA_UNIX=$(cygpath "$APPDATA")
-          list="$APPDATA_UNIX/local C:/ghcup C:/cabal"
-        else
-          list="$HOME/.local/bin $HOME/.local/state/cabal $HOME/.ghcup $HOME/.stack"
-        fi
+    # Enable for debugging, this itself takes 50 sec on Windows, in packcheck
+    # build which is tiny.
+    #- name: Check cache locations
+    #  shell: bash
+    #  run: |
+    #    # We want to see if any cache paths are symlinks; e.g. on github
+    #    # ~/.ghcup is a pre-existing symlink to /usr/local.
+    #    if [ "$RUNNER_OS" == "Windows" ]; then
+    #      # Convert Windows paths to Unix-style for Bash
+    #      APPDATA_UNIX=$(cygpath "$APPDATA")
+    #      list="$APPDATA_UNIX/local C:/ghcup C:/cabal"
+    #    else
+    #      list="$HOME/.local/bin $HOME/.local/state/cabal $HOME/.ghcup $HOME/.stack"
+    #    fi
 
-        for dir in $list; do
-          # macOS does not have --no-dereference option
-          if [ -L "$dir" ]; then
-            echo "$dir is a symlink -> $(readlink $dir)"
-          elif [ -d "$dir" ]; then
-            du -sh "$dir" 2>/dev/null || echo "$dir permission denied"
-          else
-            echo "$dir missing or not a dir"
-          fi
-        done
-        echo
-        #ls -ld $list 2>/dev/null || true
-        ls -al $list 2>/dev/null || true
+    #    for dir in $list; do
+    #      # macOS does not have --no-dereference option
+    #      if [ -L "$dir" ]; then
+    #        echo "$dir is a symlink -> $(readlink $dir)"
+    #      elif [ -d "$dir" ]; then
+    #        du -sh "$dir" 2>/dev/null || echo "$dir permission denied"
+    #      else
+    #        echo "$dir missing or not a dir"
+    #      fi
+    #    done
+    #    echo
+    #    #ls -ld $list 2>/dev/null || true
+    #    ls -al $list 2>/dev/null || true
